FROM ubuntu:22.04

ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ="Europe/Berlin"
RUN sed -e 's/archive.ubuntu.com/ftp.gwdg.de\/pub\/linux\/debian/' -i /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends gcc-9 g++-9 libopenblas-dev fftw3-dev make numdiff && \
    apt-get install -y --no-install-recommends gcc-11 g++-11 && \
    apt-get install -y --no-install-recommends clang-14 libomp-dev && \
    apt-get clean
