FROM opensuse/leap:15.4 as build_stage

ARG NUMDIFF_VERSION=5.9.0
ARG NUMDIFF_SHA512SUM=7be7aad30afbb2a964046815807be0d9149edd18364660443220ce7032248cf83bf840eaf89e19193c8c68ad075cfa81759301574ed73151526e4eea34d33f86

RUN zypper install -y make gcc10 gzip && \
        zypper addrepo https://download.opensuse.org/repositories/Base:System/standard/Base:System.repo && \
        zypper --gpg-auto-import-keys ref && \
        zypper install -y tar &&\
        zypper clean

WORKDIR /numdiff
RUN curl -s -S -L -o numdiff-${NUMDIFF_VERSION}.tar.gz https://de.freedif.org/savannah/numdiff/numdiff-${NUMDIFF_VERSION}.tar.gz && \
    echo "${NUMDIFF_SHA512SUM}  numdiff-${NUMDIFF_VERSION}.tar.gz"| sha512sum -c && \
    tar -xvf numdiff-${NUMDIFF_VERSION}.tar.gz && rm -f numdiff-${NUMDIFF_VERSION}.tar.gz
WORKDIR /numdiff/bin
RUN CC=gcc-10 ../numdiff-${NUMDIFF_VERSION}/configure && make


FROM opensuse/leap:15.4
ENV TZ="Europe/Berlin"
ENV PATH="${PATH}:/numdiff/bin"
RUN zypper install -y make gzip gcc10 gcc10-c++ blas-devel lapack-devel fftw3-devel &&\
    zypper clean

COPY --from=build_stage /numdiff /numdiff
RUN numdiff --version