matrix:
  CONTAINER_BASE:
    - ubuntu.16.04
    - ubuntu.22.04
    - almalinux.8.7
    - opensuse.leap.15.4

pipeline:
  build:
    image: gcr.io/kaniko-project/executor:debug
    commands:
      - /kaniko/executor --context . --dockerfile ci/dockerfile.${CONTAINER_BASE} --destination "ttl.sh/${CI_COMMIT_SHA}.${CONTAINER_BASE}:1h" --reproducible --use-new-run
    when:
      path:
        include: [ 'ci/dockerfile.${CONTAINER_BASE}', '.woodpecker/.ci_containers.yml' ]

when:
  path:
    include: [ 'ci/dockerfile.*', '.woodpecker/.ci_containers.yml' ]

depends_on:
  - lint