pipeline:

  build:
    image: python:3
    environment:
      - STAGE_PATH=docs/deploy
    commands:
      - pip3 install --no-cache-dir --requirement=utils/requirements.txt
      - ./utils/generate_docs.sh
      - ./utils/build_pages.sh

  check-links:
    image: quay.io/meisam/links_medics:latest
    environment:
      - STAGE_PATH=docs/deploy
    pull: true
    commands:
      - diagnose.py --version
      - diagnose.py -v --root="$STAGE_PATH" --check-external --warn-http --domain=meisam.codeberg.page

  deploy:
    image: quay.io/meisam/charliecloud:latest  ## todo: replace with ci tools container
    environment:
      - STAGE_PATH=docs/deploy
    commands:
      - ./utils/deploy_pages.sh #--verbose
    secrets: [ pages_pass ]

when:
  path:
    include: [ 'docs/*', 'utils/deploy_pages.sh', '.woodpecker/.documentation.yml' ]
  branch: master