pipeline:

  source_style:
    image: quay.io/meisam/slabcc_ci:latest
    pull: true
    group: nodep
    commands:
      - ./utils/format_check.sh
    when:
      path:
        include: [ 'src/**/*.cpp', 'src/**/*.hpp', 'utils/format_check.sh', '.clang-format', '.woodpecker/.lint.yml' ]

  shell_scripts:
    image: quay.io/meisam/slabcc_ci:latest
    group: nodep
    commands:
      - shellcheck --version
      - ls -la utils/*.sh && shellcheck utils/*.sh
    when:
      path:
        include: [ 'utils/*.sh', '.woodpecker/.lint.yml' ]

  git_repository:
    image: quay.io/meisam/slabcc_ci:latest
    group: nodep
    commands:
      - ./utils/git_check.sh
    when:
      path:
        include: [ '.gitignore', '.woodpecker/.lint.yml' ]

  documentation:
    image: quay.io/meisam/slabcc_ci:latest
    group: nodep
    commands:
      - ./utils/generate_docs.sh
      - doc8 docs/manual.rst --max-line-length 8000
    when:
      path:
        include: [ 'docs/*', '.woodpecker/.lint.yml' ]

  makefiles:
    image: cytopia/checkmake:latest
    group: nodep
    commands:
      - checkmake bin/makefile
      - checkmake tests/makefile
    when:
      path:
        include: [ 'bin/makefile', 'tests/makefile', '.woodpecker/.lint.yml' ]

  dockerfiles:
    group: nodep
    image: quay.io/meisam/trivy:latest
    pull: true
    commands:
      - trivy -v
      - trivy config --file-patterns 'dockerfile:dockerfile.*' --policy ci/.policy --severity "HIGH,CRITICAL" --exit-code 1 ci/
      - trivy config --file-patterns 'dockerfile:dockerfile.*' --policy ci/.policy --severity "LOW,MEDIUM" ci/
    when:
      path:
        include: [ 'ci/dockerfile.*', '.woodpecker/.lint.yml' ]
