pipeline:

  clang_format:
    image: ubuntu:22.04
    group: nodep
    environment:
      - CLANG_FORMAT_EXEC=clang-format-14
    commands:
      - apt update && apt install -y "$CLANG_FORMAT_EXEC"
      - ./utils/format_check.sh
    when:
      path:
        include: [ 'src/**/*.cpp', 'src/**/*.hpp', 'utils/format_check.sh', '.clang-format' ]

  shellcheck:
    image: archlinux:latest
    group: nodep
    commands:
      - pacman -Syv
      - pacman --noconfirm -S shellcheck
      - shellcheck --version
      - ls -la utils/*.sh && shellcheck utils/*.sh
    when:
      path:
        include: [ 'utils/*.sh' ]

  gitcheck:
    image: quay.io/meisam/charliecloud:latest  ## todo: replace with ci tools container
    group: nodep
    commands:
      - ./utils/git_check.sh

  rst_lint:
    image: python:3
    group: nodep
    commands:
      - pip3 install --no-cache-dir --requirement=utils/requirements.txt
      - ./utils/generate_docs.sh
      - doc8 docs/manual.rst --max-line-length 8000
    when:
      path:
        include: [ 'docs/*' ]

