matrix:
  TOOLCHAIN:
    - quay.io/meisam/ubuntu:16.04 gcc-5 g++-5 libopenblas-dev fftw3-dev
    - quay.io/meisam/ubuntu:22.04 gcc-9 g++-9 libopenblas-dev fftw3-dev
    - quay.io/meisam/ubuntu:22.04 gcc-11 g++-11 libopenblas-dev fftw3-dev
    - quay.io/meisam/ubuntu:22.04 clang-14 clang-14:clang++-14 libopenblas-dev fftw3-dev libomp-dev
    - quay.io/meisam/almalinux:8.7 gcc gcc-c++:g++ gcc-gfortran blas-devel lapack-devel fftw-devel
    - quay.io/meisam/opensuse-leap:15.4 gcc10:gcc-10 gcc10-c++:g++-10 blas-devel lapack-devel fftw3-devel
    - intel/oneapi-basekit:2023.1.0-devel-ubuntu22.04 intel-basekit:icx intel-basekit:icpx intel-oneapi-mkl-devel
    - intel/oneapi-basekit:2023.1.0-devel-ubuntu22.04 gcc-11 g++-11 intel-oneapi-mkl-devel

pipeline:
  build:
    image: ${TOOLCHAIN%% *}
    commands:
      - ./utils/setup_env.sh && . ./.env
      - cd ./bin/ && ( make || make --trace VERBOSE=1 )
      - ldd ./slabcc
      - ./slabcc --help
      - ./slabcc -v
      - ./slabcc --copyright
      - ./slabcc --man

  test:
    image: ${TOOLCHAIN%% *}
    commands:
      - ./utils/setup_env.sh && . ./.env
      - cd ./bin/ && ( make test || make test --trace VERBOSE=1 )

when:
  path:
    include: [ 'bin/*', 'src/**', 'tests/**', '.woodpecker/.slabcc.yml', 'utils/install_pkgs.sh' ]

depends_on:
  - lint